### PR TITLE
Update to jQuery 3.6.1

### PR DESCRIPTION
**Pull request by Recursing**

### CODE REVIEW

**Comment by icemac** [comment]
@Recursing I created a diff between the files downloaded from https://jquery.com/download/ and the ones you provided in your PR. The .map files differed (see my commit) – what's the reason behind?

**Comment by Recursing** [comment]
I got the files from https://github.com/jquery/jquery/releases/tag/3.6.1 , maybe the website got out of sync?

**Comment by Recursing** [comment]
image

Nevermind, they just have different filenames 🤦 . Great catch!

**Comment by janwijbrand** [comment]
Reading the conversation leads me to conclude we can merge the PR and make a release. Correct?

**Comment by janwijbrand** [comment]
I think I am correct.

**Pull request merged**
